github: add release-note description format to pull request template
tikv/pd pull request #3676
Opened 2021-05-13 08:56 UTC by CadmusJiang

Signed-off-by: Cadmus <CadmusJiang@gmail.com>

### What problem does this PR solve?
Help Tichi to realize the information collection function of release note.

### What is changed and how it works?
Add a release note reference to pull_ request_template.md
### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has configuration change
- Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tidb-ansible`](https://github.com/pingcap/tidb-ansible):
- Need to cherry-pick to the release branch

### Release note

2021-05-13 09:08 UTC, hi-rustin requested changes

2021-05-13 09:08 UTC, hi-rustin commented on .github/pull_request_template.md
> +    Some release note.
```suggestion
Please add a release note.

If you don't think this PR needs a release note then fill it with None.
```

2021-05-14 07:18 UTC, nolouch approved these changes

2021-05-14 07:24 UTC, nolouch commented
/merge

2021-05-14 07:39 UTC, hi-rustin commented
/hold

2021-05-14 07:39 UTC, hi-rustin reviewed
Better to remove it.

2021-05-14 07:39 UTC, hi-rustin commented on .github/pull_request_template.md
>  <!-- - No release note -->
```suggestion
```

2021-05-14 07:59 UTC, hi-rustin commented
/unhold

2021-05-14 08:58 UTC, JmPotato commented
/merge

2021-05-14 09:17 UTC, merged