operator: remove empty JointConsensus steps and fix single peer demote bug
tikv/pd pull request #4534
Opened 2022-01-03 05:38 UTC by matchge-ca

Signed-off-by: Hua Lu <hua.lu@pingcap.com>

### What problem does this PR solve?
Closes: #4362, #4444 

### What is changed and how it works?
- Modify condition to enable `useJointConsensus` when there is only single **non-demote** peer change
- Add logic in `execChangePeerV2` to prevent generate empty enter / leave JointConsensus steps
- Remove `allowDemote`

### Check List

Tests

- Unit test

Related changes
- Need to cherry-pick to the release branch

### Release note

```release-note
Please add a release note.

If you don't think this PR needs a release note then fill it with None.
```
None

2022-01-03 14:37 UTC, HunDunDM approved these changes

2022-01-03 14:37 UTC, HunDunDM commented on server/schedule/operator/builder_test.go
> +		name              string
Never used, cannot pass linter.

2022-01-03 14:37 UTC, HunDunDM commented on server/schedule/operator/builder.go
> +	} else {
```suggestion
		}
		return
	}
```

2022-01-03 14:37 UTC, HunDunDM commented on server/schedule/operator/builder.go
> +		} else if !core.IsLearner(o) && core.IsLearner(n) {
`core.IsLearner` is called repeatedly.

2022-01-04 01:17 UTC, HunDunDM commented
/lgtm cancel

2022-01-04 01:18 UTC, HunDunDM commented
The previous lgtm was a misoperation, sorry.

2022-01-04 01:21 UTC, HunDunDM requested changes
The previous lgtm was a misoperation, sorry.

2022-01-05 06:51 UTC, HunDunDM reviewed
rest LGTM

2022-01-05 06:51 UTC, HunDunDM commented on server/schedule/operator/builder.go
> +	} else {
The content in the `else` is too long. In fact, `len(b.toPromote)+len(b.toDemote) == 0` is only a special case, so you can `return` directly in the `if`, and no `else` is needed later.

2022-01-05 06:51 UTC, HunDunDM commented on server/schedule/operator/builder.go
> +		// No need to add empty enter / leave joint consensus step if no peer in toPromote and toDemote
```suggestion
		// No need to add empty enter / leave joint consensus step if no peer in `toPromote` and `toDemote`
```

2022-01-06 03:42 UTC, HunDunDM approved these changes

2022-01-06 03:45 UTC, HunDunDM commented
ref https://github.com/tikv/tikv/issues/11463

2022-01-06 04:00 UTC, disksing approved these changes

2022-01-06 04:00 UTC, disksing commented
/merge

2022-01-06 04:02 UTC, merged