config: migrate test framework to testify
tikv/pd pull request #5103
Opened 2022-06-06 04:32 UTC by rleungx

Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Ref #4813.

### What is changed and how does it work?
Just as the title says.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

2022-06-06 06:35 UTC, JmPotato commented on server/config/config_test.go
>  }
Should be removed.

2022-06-06 06:35 UTC, JmPotato commented on server/config/config_test.go
> +	re.NotNil(cfg.Adjust(nil, false))
Better use `re.NoError `here.

2022-06-06 06:35 UTC, JmPotato commented on server/config/config_test.go
> +	re.Nil(opt.Persist(storage))
Ditto.

2022-06-06 06:35 UTC, JmPotato commented on server/config/config_test.go
> +	re.Nil(newOpt.Reload(storage))
Same as above.

2022-06-06 06:35 UTC, JmPotato commented on server/config/config_test.go
> +	re.True(reflect.DeepEqual(cfg.Clone(), cfg))
`require.Equal` is `reflect.DeepEqual` actually. See https://github.com/tikv/pd/issues/5104.

2022-06-06 09:48 UTC, JmPotato approved these changes

2022-06-06 09:49 UTC, JmPotato requested changes

2022-06-06 09:49 UTC, JmPotato commented on server/config/config_test.go
> +	re.True(strings.Contains(cfg.WarningMsgs[0], "Config contains undefined item"))
This could use `re.Contains` to check.

2022-06-06 09:49 UTC, JmPotato commented on server/config/config_test.go
> +	re.False(strings.Contains(string(b), "disable-remove-down-replica"))
Ditto.

2022-06-07 03:44 UTC, JmPotato approved these changes

2022-06-07 05:44 UTC, lhy1024 approved these changes

2022-06-07 05:51 UTC, JmPotato commented
/merge

2022-06-07 06:02 UTC, merged