pkg: fix bugs that the report interval equals the avg interval
tikv/pd pull request #6302
Opened 2023-04-11 10:42 UTC by bufferflies

### What problem does this PR solve?

Issue Number: Close #6301

### What is changed and how does it work?
the equal always be true if the report interval is equal the avg interval
https://github.com/tikv/pd/blob/ce053eb3201fb62942627e3e014bd274d8ff8922/pkg/movingaverage/avg_over_time.go#L87-L91

```commit-message
```

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

### Release note

```release-note
None.
```

2023-04-11 13:24 UTC, lhy1024 requested changes
aot.GetInstantaneous() should also return rate.

2023-04-11 13:24 UTC, lhy1024 commented on pkg/movingaverage/avg_over_time.go
> +		return aot.margin.delta
```suggestion
		return aot.margin.delta/aot.margin.interval
```

2023-04-11 13:24 UTC, lhy1024 commented on pkg/movingaverage/avg_over_time_test.go
> +	re.Equal(float64(1000), aot.GetInstantaneous())
```suggestion
	re.Equal(float64(1000)/dur, aot.GetInstantaneous())
```

2023-04-11 13:24 UTC, lhy1024 commented on pkg/movingaverage/avg_over_time_test.go
> +	re.Equal(float64(1000), aot.GetInstantaneous())
ditto

2023-04-12 02:14 UTC, bufferflies commented on pkg/movingaverage/avg_over_time.go
> +		return aot.margin.delta
fixed

2023-04-12 02:15 UTC, bufferflies commented on pkg/movingaverage/avg_over_time_test.go
> +	re.Equal(float64(1000), aot.GetInstantaneous())
fixed

2023-04-12 03:11 UTC, lhy1024 approved these changes

2023-04-12 12:25 UTC, nolouch approved these changes

2023-04-12 12:25 UTC, nolouch commented
/merge

2023-04-12 12:35 UTC, merged